rules:
  property-sort-order:
    - 2
  force-element-nesting:
    - 0
  no-color-literals:
    - 2
    -
      allow-rgba: true
  no-url-protocols:
    - 0
  nesting-depth:
    - 2
    -
      max-depth: 4
  no-vendor-prefixes:
    - 0
  class-name-format:
    - 2
    -
      convention: 'camelcase'
files:
  ignore:
    - 'node_modules/**/*.scss'
    - 'node_modules/**/*.sass'
    - 'app/styles/base/**/*'
